= Multi-Protocol Networking Library

image:https://circleci.com/gh/cesanta/fossa.svg?style=shield[Build Status,link=https://circleci.com/gh/cesanta/fossa/tree/master]
image:http://img.shields.io/coveralls/cesanta/fossa/master.svg[Coverage Status,link=https://coveralls.io/r/cesanta/fossa?branch=master]
image:https://img.shields.io/badge/license-GPL_2-green.svg[License,link=https://github.com/cesanta/fossa/blob/master/LICENSE]

Fossa is a
http://cesanta.com/fossa.shtml[multi-protocol networking library] written in C.
It provides easy to use event-driven interface that allows to implement
network protocols or scalable network applications  with little effort.
Fossa helps developers to manage the complexity of network programming
and let them concentrate on the logic, saving time and money.

Fossa has built-in support for several protocols, like
HTTP, Websocket, MQTT, mDNS. Example applications include
Websocket-based chat server, JSON-RPC server,
database server with RESTful API, MQTT broker, netcat with SSL and hexdump,
Raspberry PI camera video feed + led control, and more.

Fossa is ideal for the embedded environments, it has been designed as
an open source platform for connecting devices and bringing them online.

== Features

* Cross-platform: works on Linux/UNIX, QNX, eCos, Windows, Android, iPhone, etc
* Single-threaded, asynchronous, non-blocking core with simple event-based API
* Builtin protocols:
  ** plain TCP, plain UDP, SSL/TLS (over TCP, one-way or two-way)
  ** HTTP client, HTTP server
  ** Websocket client, Websocket server
  ** JSON-RPC client, JSON-RPC server
  ** MQTT client, MQTT broker
  ** DNS client, DNS server, async DNS resolver
* Tiny static and run-time footprint
* Source code is both ISO C and ISO C++ compliant
* Very easy to integrate: just copy
  https://raw.githubusercontent.com/cesanta/fossa/master/fossa.c[fossa.c] and
  https://raw.githubusercontent.com/cesanta/fossa/master/fossa.h[fossa.h]
  files to your build tree
* Extensively tested and production-ready, trusted by many blue chip businesses

== Examples & Documentation

- link:http://cesanta.com/docs/fossa[User Guide] - Detailed User Guide and API reference
- link:examples[] - Collection of well-commented examples. To build any example,
go into respective directory and type `make`

== License

Fossa is released under
http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU GPL v.2].
Businesses have an option to get non-restrictive, royalty-free commercial
license and professional support from http://cesanta.com[Cesanta Software].
